### PR TITLE
Clarification of "the significant change" on link

### PR DESCRIPTION
**Pull request by tomaszmrugalski**
This PR is about resolving issues raised during WGLC by Esko Dijk. The [initial proposals](https://mailarchive.ietf.org/arch/msg/dhcwg/BtE7OBvoysnm0kySMYum9EUqEYc/) called for 5 changes:
1. rejected as it would change the normative language.
2. the requirement to send confirm,renew or inf-request needs to be clarified - discussion in progress
3. already applied on this PR
4. the M bit is informative.
5. I would be hesitant to add new normative language to add any extra delays.

I already applied changes proposed by Esko in his Nov. 11 mail regarding 3 (clarify the text significant changes).

### CODE REVIEW

**Comment by EskoDijk** [comment]
Thanks @tomaszmrugalski , building further on my email response to Tim of Nov 17 2023, I'm proposing to add the following item to the bullet list of examples in 18.2.12:

```
* The client’s network interface indicates a disconnection event, followed by a connection event.
```

**Comment by tomaszmrugalski** [comment]
> I'm proposing to add the following item to the bullet list of examples in 18.2.12:
> 
> ```
> * The client’s network interface indicates a disconnection event, followed by a connection event.
> ```
Thanks for the text. Looks good to me. Added.

**Comment by EskoDijk** [comment]
@tomaszmrugalski  here below for completeness the updated text for point 2. as I proposed on the list:

OLD: 

If not associated with one of the above-mentioned conditions, a client SHOULD initiate a Renew/Reply exchange (as if the T1 time expired) as described in Section 18.2.4 or an Information-request/Reply exchange as described in Section 18.2.6 if the client detects a significant change regarding the prefixes available on the link (when new prefixes are added or existing prefixes are deprecated), as this may indicate a configuration change. However, a client MUST rate‑limit such attempts to avoid flooding a server with requests when there are link issues (for example, only doing one of these at most every 30 seconds).

NEW:

If not associated with a detection of having moved to a new link, a client SHOULD initiate one of the Renew/Reply, Confirm/Reply or Information-request/Reply exchanges, if the client detects a significant change regarding the prefixes available on the link. A change is considered significant when one or more on-link prefixes are added, and/or one or more existing on-link prefixes are deprecated. The reason for this is that such a significant change may indicate a configuration change at the server. However, a client MUST rate‑limit such exchange attempts to avoid flooding a server with requests when there are link issues (for example, only doing one of these at most every 30 seconds).

The above selection of an exchange to initiate depends on the client's current state:
1. If the client has any valid delegated prefixes obtained from the server, it sends Renew (as if the T1 time expired) as described in Section 18.2.4.
2. Else, if the client obtained address(es) from the server, it sends Confirm as described in Section 18.2.3.
3. Else, if only network information was obtained from the server, it sends Information-request as described in Section 18.2.6.

**Comment by mcr** [comment]
> @tomaszmrugalski here below for completeness the updated text for point 2. as I proposed on the list:
> NEW:

I put this into commit a0037bbde069593d945c138116af9866d141dfd3. Please check.

**Review by mcr — APPROVED** [review]

**Comment by EskoDijk** [comment]
@mcr Thanks for integrating: text looks ok. The new <li> items still need their closing </li> element; as we're not in HTML country :-)

**Comment by tomaszmrugalski** [comment]
> element; as we're not in HTML country :-)

Fixed. Thanks for donating the text. MCR already approved, and it looks good to me, too.

**Pull request merged**
