### PR TITLE
Updated UDP port text and removed IA Addr requirement to be IA_NA.

### PR DESCRIPTION
**Pull request by twintersunh**

### CODE REVIEW

**Comment by bevolz** [comment]
Hi Tim:In general, looks great. However, the new section for IA Address Option:      <section anchor="RFC3315-22.6" numbered="true" toc="default">        <name>IA Address Option</name>        <t>The IA Address option is used to specify an address associated        with an IA_NA. The IAaddr‑options field encapsulates those options that are        specific to this address.</t>        <t>The format of the IA Address option is:</t>Is not necessarily much better as it still ties this option to IA_NA which it isn’t in a Leasequrery nor in the address notification work.I wonder whether the following is better:     <section anchor="RFC3315-22.6" numbered="true" toc="default">
     <name>IA Address Option</name>
     <t>The IA Address option is used to specify an address.
     In this document it is only used encapsulated within an IA_NA.
     The IAaddr options field encapsulates those options that are
     specific to this address.</t>
     <t>The format of the IA Address option is:</t>Or something like that. We could reference that it is used elsewhere in Leasequery (RFC 5007) and the new address notification RFC <to be>, but not sure that is necessary?- Bernie (from iPad)On Jul 5, 2024, at 12:26 PM, Timothy Winters ***@***.***> wrote:﻿



You can view, comment on, or merge this pull request online at:
  https://github.com/dhcwg/rfc8415bis/pull/11

Commit Summary

  4150a23  Updated UDP port text and removed IA Addr requirement to be IA_NA.


File Changes  (1 file)

  
    M
    draft-ietf-dhc-rfc8415bis.xml
    (15)
  


Patch Links:

  https://github.com/dhcwg/rfc8415bis/pull/11.patch
  https://github.com/dhcwg/rfc8415bis/pull/11.diff

**Comment by bevolz** [comment]
Oh, and thanks for working on this!

If and when we’re ready to publish, I’m happy to do a final review comparing current published with new.

- Bernie (from iPad)

**Comment by mcr** [comment]
go ahead. Please be more careful about "git commit -a", it's always never the right choice.

**Review by mcr — APPROVED** [review]

**Comment by tomaszmrugalski** [comment]
I've reviewed those changes and they look good. I particularly like the port clarification.

**Review by tomaszmrugalski — APPROVED** [review]

**Comment by tomaszmrugalski** [comment]
And thanks for moving forward with this!

**Comment by twintersunh** [comment]
I reverted my bad commit, my apologies for the noise.  I made changes based on Bernie's feedback.

**Comment by bevolz** [comment]
Hi Tim:Thanks …        The IA Address option is used to specify an address.
        In this document it is only specified to be encapsulated within an
        IA_NA.  DHCPv6 Leasequery <xref target="RFC5007" format="default"/> specifies
        using of the IA Address Option. The IAaddr‑options field encapsulates those
        options that arespecific to this address.

However, a space is missing in “arespecific” and it might be better to say:

        DHCPv6 Leasequery <xref target="RFC5007" format="default"/> makes
        use of the IA Address Option without encapsulating it in IA_NA.- Bernie (from iPad)On Jul 8, 2024, at 2:40 PM, Timothy Winters ***@***.***> wrote:﻿
I reverted my bad commit, my apologies for the noise.  I made changes based on Bernie's feedback.

**Comment by twintersunh** [comment]
Thanks for the quick review Bernie.  Made the changes.

**Pull request merged**
